[build]
  publish = "."

[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"

[[edge_functions]]
  function = "social-preview"
  path = "/*"
